/** Profile H 1.0 canonical DAG-JSON and x402 v2 codecs. */
import { createHash } from 'node:crypto';

export type ProfileHErrorCode =
  | 'H_INVALID_PAYMENT_MESSAGE' | 'H_LIMIT_EXCEEDED' | 'H_UNSUPPORTED_X402_VERSION'
  | 'H_UNSUPPORTED_NETWORK' | 'H_AMOUNT_MISMATCH' | 'H_QUOTE_EXPIRED'
  | 'H_VERIFICATION_FAILED' | 'H_ENTITLEMENT_EXHAUSTED' | 'H_REQUEST_MISMATCH'
  | 'H_PAYMENT_REPLAY';

export class ProfileHValidationError extends Error {
  constructor(public readonly code: ProfileHErrorCode, public readonly path: string, message: string) {
    super(message); this.name = 'ProfileHValidationError';
  }
}

export interface ProfileHLimits {
  max_artifact_bytes:number; max_x402_bytes:number; max_requirements:number;
  max_depth:number; max_string_bytes:number; max_parents:number; max_quote_lifetime_ms:number;
}
export const DEFAULT_PROFILE_H_LIMITS:ProfileHLimits={max_artifact_bytes:1048576,max_x402_bytes:32768,max_requirements:8,max_depth:16,max_string_bytes:8192,max_parents:32,max_quote_lifetime_ms:300000};
const HARD:ProfileHLimits={max_artifact_bytes:16777216,max_x402_bytes:262144,max_requirements:32,max_depth:32,max_string_bytes:65536,max_parents:256,max_quote_lifetime_ms:3600000};
const MAX=9007199254740991, B32='abcdefghijklmnopqrstuvwxyz234567';
const SCHEMAS:Record<string,string>={PaidCapability:'paid-capability',PaymentQuote:'payment-quote',PaymentAuthorization:'payment-authorization',PaymentVerification:'payment-verification',SettlementReceipt:'settlement-receipt',PaidEntitlement:'paid-entitlement',UsageRecord:'usage-record',RefundRecord:'refund-record',AccessReceipt:'access-receipt'};
const FIELDS:Record<string,string[]>={
 PaidCapability:'serverDid descriptorCid interfaceCid operationKind operationName httpMethod httpRoute catalogVersion ability policyCid termsCid scheme network asset amount payee validFrom expiresAt settlementTiming sellerDid signatureAlg signature'.split(' '),
 PaymentQuote:'capabilityCid catalogCid descriptorCid requestCid requirements nonce expiresAt idempotencyKey sellerDid signatureAlg signature'.split(' '),
 PaymentAuthorization:'quoteCid requestCid requirementIndex paymentPayloadCid payerCommitment signedPayloadCommitment signatureCommitment'.split(' '),
 PaymentVerification:'authorizationCid verifierDid decision reasonCode verifiedAt expiresAt evidenceCid'.split(' '),
 SettlementReceipt:'verificationCid outcome amount network networkReferenceCommitment disclosurePolicy paymentResponseCid settledAt'.split(' '),
 PaidEntitlement:'settlementCid subjectCommitment capabilityCid quotaUnits consumedUnits unit expiresAt'.split(' '),
 UsageRecord:'entitlementCid unit inputCid outputCid units recordedAt'.split(' '),
 RefundRecord:'settlementCid requestCid decision outcome evidenceCid requestedAt decidedAt'.split(' '),
 AccessReceipt:'operationName requestCid ucanDecisionCid policyDecisionCid leaseDecisionCid commercialEvidenceCid decision resultCid reasonCode decidedAt'.split(' '),
};
const COMMON=['schema','createdAt','parents','correlationId'];
const FORBIDDEN=new Set('privatekey seedphrase mnemonic authenticationcookie fullucan requestarguments paymentsignature paymentpayload facilitatorresponse walletaddress transactionhash rawsignature'.split(' '));

function fail(path:string,message:string,code:ProfileHErrorCode='H_INVALID_PAYMENT_MESSAGE'):never{throw new ProfileHValidationError(code,path,message);}
function object(v:unknown,p=''):Record<string,any>{if(v===null||typeof v!=='object'||Array.isArray(v))fail(p,'must be an object');return v as Record<string,any>;}
function integer(v:unknown,p:string,lo=0,hi=MAX):number{if(typeof v!=='number'||!Number.isSafeInteger(v)||Object.is(v,-0)||v<lo||v>hi)fail(p,`must be an integer in [${lo}, ${hi}]`);return v;}
function string(v:unknown,p:string,max=8192,empty=false):string{if(typeof v!=='string'||(!empty&&!v.length)||v.includes('\0')||Buffer.byteLength(v)>max)fail(p,'invalid string');return v;}
function oneOf(v:unknown,p:string,values:string[]):string{const x=string(v,p);if(!values.includes(x))fail(p,'unsupported value');return x;}
function limits(x:Partial<ProfileHLimits>={}):ProfileHLimits{const out={...DEFAULT_PROFILE_H_LIMITS};for(const [k,v] of Object.entries(x)){if(!(k in out))fail('/limits',`unknown limit ${k}`);integer(v,`/limits/${k}`,1,HARD[k as keyof ProfileHLimits]);(out as any)[k]=v;}return out;}
function walk(v:unknown,l:ProfileHLimits,p='',depth=0):void{if(depth>l.max_depth)fail(p,'JSON nesting exceeds negotiated bound','H_LIMIT_EXCEEDED');if(v===null||typeof v==='boolean')return;if(typeof v==='number'){integer(v,p,-MAX,MAX);return;}if(typeof v==='string'){if(Buffer.byteLength(v)>l.max_string_bytes||v.includes('\0'))fail(p,'string exceeds negotiated bound','H_LIMIT_EXCEEDED');return;}if(Array.isArray(v)){v.forEach((x,i)=>walk(x,l,`${p}/${i}`,depth+1));return;}const o=object(v,p);for(const [k,x] of Object.entries(o))walk(x,l,`${p}/${k}`,depth+1);}
function compare(a:string,b:string):number{return Buffer.compare(Buffer.from(a),Buffer.from(b));}
function canonical(v:unknown,l:ProfileHLimits,p=''):string{if(v===null)return'null';if(typeof v==='boolean')return v?'true':'false';if(typeof v==='number'){integer(v,p,-MAX,MAX);return String(v);}if(typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map((x,i)=>canonical(x,l,`${p}/${i}`)).join(',')+']';const o=object(v,p),ks=Object.keys(o).sort(compare);return'{'+ks.map(k=>JSON.stringify(k)+':'+canonical(o[k],l,`${p}/${k}`)).join(',')+'}';}
export function canonicalProfileHBytes(v:unknown,overrides:Partial<ProfileHLimits>={}):Uint8Array{const l=limits(overrides);walk(v,l);return Buffer.from(canonical(v,l));}
function base32(bytes:Uint8Array):string{let out='',bits=0,acc=0;for(const x of bytes){acc=(acc<<8)|x;bits+=8;while(bits>=5){bits-=5;out+=B32[(acc>>bits)&31]!;acc&=(1<<bits)-1;}}if(bits)out+=B32[(acc<<(5-bits))&31]!;return out;}
export function profileHArtifactCid(v:unknown,overrides:Partial<ProfileHLimits>={}):string{const d=createHash('sha256').update(canonicalProfileHBytes(v,overrides)).digest();return'b'+base32(Uint8Array.from([1,0xa9,0x02,0x12,0x20,...d]));}
function varint(b:Uint8Array,start:number):[number,number]{let n=0,s=0,i=start;for(;i<b.length&&s<56;i++,s+=7){const x=b[i]!;n+=(x&127)*2**s;if(!(x&128))return[n,i+1];}fail('','invalid CID');}
function cid(v:unknown,p:string):void{const x=string(v,p,128);if(!/^b[a-z2-7]+$/.test(x))fail(p,'CID must be lowercase base32 CIDv1');let bits=0,acc=0;const out:number[]=[];for(const ch of x.slice(1)){const z=B32.indexOf(ch);acc=(acc<<5)|z;bits+=5;if(bits>=8){bits-=8;out.push((acc>>bits)&255);acc&=(1<<bits)-1;}}const b=Uint8Array.from(out),[ver,a]=varint(b,0),[codec,z]=varint(b,a),[mh,n]=varint(b,z),[len,e]=varint(b,n);if(ver!==1||codec!==0x129||mh!==0x12||len!==32||e+len!==b.length)fail(p,'CID must be CIDv1 dag-json sha2-256');}
function did(v:unknown,p:string):void{if(!/^did:[a-z0-9]+:[A-Za-z0-9._:%-]+(?:[/?#][^\0]*)?$/.test(string(v,p,512)))fail(p,'invalid DID');}
function amount(v:unknown,p:string):void{if(typeof v!=='string'||!/^(?:0|[1-9][0-9]{0,77})$/.test(v))fail(p,'amount must be a canonical non-negative atomic decimal','H_AMOUNT_MISMATCH');}
function network(v:unknown,p:string):void{if(!/^[a-z0-9-]{3,8}:[A-Za-z0-9_-]{1,32}$/.test(string(v,p,64)))fail(p,'network must be a canonical CAIP-2 identifier','H_UNSUPPORTED_NETWORK');}
function signature(v:unknown,p:string):void{const x=string(v,p,128);if(!/^[A-Za-z0-9_-]{86}$/.test(x)){fail(p,'signature must be unpadded base64url Ed25519 bytes','H_VERIFICATION_FAILED');}try{if(Buffer.from(x,'base64url').length!==64)fail(p,'invalid signature encoding','H_VERIFICATION_FAILED');}catch{fail(p,'invalid signature encoding','H_VERIFICATION_FAILED');}}
function redact(v:unknown,p=''):void{if(Array.isArray(v)){v.forEach((x,i)=>redact(x,`${p}/${i}`));return;}if(v&&typeof v==='object'){for(const [k,x] of Object.entries(v)){if(FORBIDDEN.has(k.toLowerCase().replace(/[^a-z0-9]/g,'')))fail(`${p}/${k}`,'sensitive field is forbidden in a Profile H artifact');redact(x,`${p}/${k}`);}}}
function requirement(v:unknown,p:string):void{const o=object(v,p),keys=['amount','asset','extra','maxTimeoutSeconds','network','payTo','scheme'];if(JSON.stringify(Object.keys(o).sort())!==JSON.stringify(keys))fail(p,'invalid x402 requirement fields');string(o['scheme'],p+'/scheme',64);network(o['network'],p+'/network');string(o['asset'],p+'/asset',256);amount(o['amount'],p+'/amount');string(o['payTo'],p+'/payTo',256);integer(o['maxTimeoutSeconds'],p+'/maxTimeoutSeconds',1,3600);object(o['extra'],p+'/extra');}

export function validateProfileHArtifact(kind:string,value:unknown,overrides:Partial<ProfileHLimits>={},nowMs?:number):string{
 const l=limits(overrides);if(!(kind in SCHEMAS))fail('/kind','unknown Profile H artifact kind');const o=object(value),allowed=new Set([...COMMON,...FIELDS[kind]!]);for(const k of Object.keys(o))if(!allowed.has(k))fail('/'+k,'unknown field');for(const k of allowed)if(!(k in o))fail('/'+k,'required field missing');if(o['schema']!==`mcp++/profile-h/${SCHEMAS[kind]}@1.0`)fail('/schema','wrong schema marker');integer(o['createdAt'],'/createdAt');if(!Array.isArray(o['parents'])||o['parents'].length>l.max_parents)fail('/parents','parent count exceeds negotiated bound','H_LIMIT_EXCEEDED');o['parents'].forEach((x:unknown,i:number)=>{cid(x,`/parents/${i}`);if(i&&compare(o['parents'][i-1],x as string)>=0)fail(`/parents/${i}`,'parents must be UTF-8 sorted and unique');});string(o['correlationId'],'/correlationId',128);redact(o);specific(kind,o,l,nowMs);if(canonicalProfileHBytes(o,l).length>l.max_artifact_bytes)fail('','artifact exceeds negotiated bound','H_LIMIT_EXCEEDED');return profileHArtifactCid(o,l);
}
function specific(k:string,o:Record<string,any>,l:ProfileHLimits,now?:number):void{const c=(n:string)=>cid(o[n],'/'+n),s=(n:string,m=8192)=>string(o[n],'/'+n,m),i=(n:string,a=0,b=MAX)=>integer(o[n],'/'+n,a,b);switch(k){
 case'PaidCapability':did(o['serverDid'],'/serverDid');c('descriptorCid');c('interfaceCid');oneOf(o['operationKind'],'/operationKind',['tool','resource','prompt','http']);s('operationName',256);if(o['httpMethod']!==null)oneOf(o['httpMethod'],'/httpMethod',['GET','POST','PUT','PATCH','DELETE']);if(o['httpRoute']!==null)s('httpRoute',512);s('catalogVersion',64);s('ability',256);c('policyCid');c('termsCid');s('scheme',64);network(o['network'],'/network');s('asset',256);amount(o['amount'],'/amount');s('payee',256);i('validFrom');i('expiresAt');if(o['expiresAt']<=o['validFrom'])fail('/expiresAt','expiry must follow validity start','H_QUOTE_EXPIRED');oneOf(o['settlementTiming'],'/settlementTiming',['immediate','metered','batched']);did(o['sellerDid'],'/sellerDid');oneOf(o['signatureAlg'],'/signatureAlg',['Ed25519']);signature(o['signature'],'/signature');break;
 case'PaymentQuote':['capabilityCid','catalogCid','descriptorCid','requestCid'].forEach(c);if(!Array.isArray(o['requirements'])||o['requirements'].length<1||o['requirements'].length>l.max_requirements)fail('/requirements','requirements count exceeds negotiated bound','H_LIMIT_EXCEEDED');o['requirements'].forEach((x:unknown,j:number)=>requirement(x,`/requirements/${j}`));s('nonce',128);i('expiresAt');s('idempotencyKey',128);did(o['sellerDid'],'/sellerDid');oneOf(o['signatureAlg'],'/signatureAlg',['Ed25519']);signature(o['signature'],'/signature');if(o['expiresAt']<=o['createdAt']||o['expiresAt']-o['createdAt']>l.max_quote_lifetime_ms||(now!==undefined&&now>=o['expiresAt']))fail('/expiresAt','quote is expired or exceeds negotiated lifetime','H_QUOTE_EXPIRED');break;
 case'PaymentAuthorization':c('quoteCid');c('requestCid');i('requirementIndex',0,l.max_requirements-1);['paymentPayloadCid','payerCommitment','signedPayloadCommitment','signatureCommitment'].forEach(c);break;
 case'PaymentVerification':c('authorizationCid');did(o['verifierDid'],'/verifierDid');oneOf(o['decision'],'/decision',['verified','rejected']);s('reasonCode',128);i('verifiedAt');i('expiresAt');c('evidenceCid');if(o['expiresAt']<=o['verifiedAt']||(now!==undefined&&now>=o['expiresAt']))fail('/expiresAt','verification freshness expired','H_VERIFICATION_FAILED');break;
 case'SettlementReceipt':c('verificationCid');oneOf(o['outcome'],'/outcome',['settled','failed','pending','reconciliation-required','refunded']);amount(o['amount'],'/amount');network(o['network'],'/network');c('networkReferenceCommitment');oneOf(o['disclosurePolicy'],'/disclosurePolicy',['commitment-only','authorized','public']);c('paymentResponseCid');i('settledAt');break;
 case'PaidEntitlement':c('settlementCid');c('subjectCommitment');c('capabilityCid');i('quotaUnits');i('consumedUnits');s('unit',128);i('expiresAt');if(o['consumedUnits']>o['quotaUnits'])fail('/consumedUnits','entitlement quota exhausted','H_ENTITLEMENT_EXHAUSTED');if(now!==undefined&&now>=o['expiresAt'])fail('/expiresAt','entitlement expired','H_ENTITLEMENT_EXHAUSTED');break;
 case'UsageRecord':c('entitlementCid');s('unit',128);c('inputCid');c('outputCid');i('units',1);i('recordedAt');break;
 case'RefundRecord':c('settlementCid');c('requestCid');oneOf(o['decision'],'/decision',['requested','approved','denied']);oneOf(o['outcome'],'/outcome',['pending','refunded','failed','not-applicable']);c('evidenceCid');i('requestedAt');i('decidedAt');if(o['decidedAt']<o['requestedAt'])fail('/decidedAt','decision precedes request');break;
 case'AccessReceipt':s('operationName',256);c('requestCid');['ucanDecisionCid','policyDecisionCid','leaseDecisionCid','commercialEvidenceCid'].forEach(n=>{if(o[n]!==null)c(n);});oneOf(o['decision'],'/decision',['allow','deny']);if(o['resultCid']!==null)c('resultCid');s('reasonCode',128);i('decidedAt');if(o['decision']==='allow'&&(o['commercialEvidenceCid']===null||o['resultCid']===null))fail('/commercialEvidenceCid','allow requires commercial evidence and result');break;
 }}

function validateX402(kind:string,o:Record<string,any>,l:ProfileHLimits):void{let allowed:string[],required:string[];if(kind==='PaymentRequired'){allowed=['x402Version','error','resource','accepts','extensions'];required=['x402Version','accepts'];}else if(kind==='PaymentPayload'){allowed=['x402Version','resource','accepted','payload','extensions'];required=['x402Version','accepted','payload'];}else if(kind==='SettlementResponse'){allowed=['success','errorReason','transaction','network','payer','extensions'];required=['success','network'];}else fail('/kind','unknown x402 object kind');if(required.some(x=>!(x in o))||Object.keys(o).some(x=>!allowed.includes(x)))fail('','invalid x402 object fields');if(kind!=='SettlementResponse'&&o['x402Version']!==2)fail('/x402Version','only x402 v2 is supported','H_UNSUPPORTED_X402_VERSION');if(kind==='PaymentRequired'){if(!Array.isArray(o['accepts'])||o['accepts'].length<1||o['accepts'].length>l.max_requirements)fail('/accepts','requirements count exceeds negotiated bound','H_LIMIT_EXCEEDED');o['accepts'].forEach((x:unknown,i:number)=>requirement(x,`/accepts/${i}`));}else if(kind==='PaymentPayload'){requirement(o['accepted'],'/accepted');object(o['payload'],'/payload');}else{if(typeof o['success']!=='boolean')fail('/success','must be boolean');network(o['network'],'/network');if(o['transaction']!==undefined&&o['transaction']!==null)string(o['transaction'],'/transaction',512);}}
export function encodeX402Header(kind:string,value:unknown,overrides:Partial<ProfileHLimits>={}):string{const l=limits(overrides),o=object(value);validateX402(kind,o,l);const raw=canonicalProfileHBytes(o,l);if(raw.length>l.max_x402_bytes)fail('','decoded x402 object exceeds negotiated bound','H_LIMIT_EXCEEDED');return Buffer.from(raw).toString('base64');}
export function decodeX402Header(kind:string,encoded:string,overrides:Partial<ProfileHLimits>={}):Record<string,any>{const l=limits(overrides);if(typeof encoded!=='string'||!encoded||/\s/.test(encoded)||encoded.length>Math.ceil(l.max_x402_bytes/3)*4)fail('/header','invalid or oversized base64',encoded?'H_LIMIT_EXCEEDED':'H_INVALID_PAYMENT_MESSAGE');if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(encoded))fail('/header','invalid base64');const raw=Buffer.from(encoded,'base64');if(raw.length>l.max_x402_bytes)fail('/header','decoded x402 object exceeds negotiated bound','H_LIMIT_EXCEEDED');let value:unknown;try{value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(raw));}catch{fail('/header','invalid UTF-8 or JSON');}walk(value,l);const o=object(value);validateX402(kind,o,l);if(!Buffer.from(canonicalProfileHBytes(o,l)).equals(raw))fail('/header','x402 JSON is not canonically encoded');return o;}
export function validateRequestBinding(expected:string,artifact:Record<string,unknown>):void{cid(expected,'/expectedRequestCid');if(artifact['requestCid']!==expected)fail('/requestCid','payment is bound to a different request','H_REQUEST_MISMATCH');}
export function validateReplay(seen:Set<string>,commitment:string):void{cid(commitment,'/commitment');if(seen.has(commitment))fail('/commitment','payment authorization was already consumed','H_PAYMENT_REPLAY');}
