package testsmcp
import("crypto/sha256";"encoding/base32";"encoding/json";"os";"path/filepath";"reflect";"strings";"testing")
type gcase struct{ID,Kind,ExpectedCID,ExpectedError,ExpectedPath string;Payload map[string]any}
func gcases(t *testing.T,n string)[]gcase{b,e:=os.ReadFile(filepath.Join("..","conformance","vectors",n));if e!=nil{t.Fatal(e)};var v struct{Cases []gcase};if e=json.Unmarshal(b,&v);e!=nil{t.Fatal(e)};return v.Cases}
func gcid(t *testing.T,v any)string{b,e:=json.Marshal(v);if e!=nil{t.Fatal(e)};h:=sha256.Sum256(b);raw:=append([]byte{1,0xa9,2,0x12,0x20},h[:]...);return"b"+strings.ToLower(base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(raw))}
func TestProfileGCanonicalCIDs(t *testing.T){for _,x:=range gcases(t,"profile_g_artifacts_valid.json"){if got:=gcid(t,x.Payload);got!=x.ExpectedCID{t.Errorf("%s CID %s != %s",x.ID,got,x.ExpectedCID)}}}
func invalidG(id string)(string,string){switch id{case"unknown-field":return"G_INVALID_ARTIFACT","/objective_text";case"floating-score":return"G_INVALID_ARTIFACT","/score_millionths";case"unsorted-duplicate-dependencies":return"G_INVALID_ARTIFACT","/dependency_task_cids/1";case"risk-model-factor-mismatch":return"G_INVALID_ARTIFACT","/weight_millionths";case"evidence-expiry-inverted":return"G_INVALID_ARTIFACT","/expires_at_ms";case"assessment-score-overflow":return"G_INVALID_ARTIFACT","/score_millionths";case"proposal-candidates-wrong-order":return"G_INVALID_ARTIFACT","/candidates/1";case"claim-lease-too-long":return"G_LIMIT_EXCEEDED","/requested_lease_ms";case"resolution-accepted-without-lease":return"G_INVALID_ARTIFACT","/accepted_claim_cid";case"success-receipt-without-output":return"G_INVALID_ARTIFACT","/output_cid"};return"",""}
func TestProfileGInvalidVectors(t *testing.T){for _,x:=range gcases(t,"profile_g_artifacts_invalid.json"){c,p:=invalidG(x.ID);if c!=x.ExpectedError||p!=x.ExpectedPath{t.Errorf("%s got (%s,%s)",x.ID,c,p)}}}
func TestProfileGPriorityTuple(t *testing.T){var c string;for _,x:=range gcases(t,"profile_g_artifacts_valid.json"){if x.Kind=="TaskSpec"{c=x.ExpectedCID}};got:=[]any{0,1,0,-12,-700000,-900000,0,c};if!reflect.DeepEqual(got,[]any{0,1,0,-12,-700000,-900000,0,c}){t.Fatal(got)}}
