#!/usr/bin/env python3
"""Generate MCP++ JSON Schemas from one canonical source (SchemaId@1).

Authority
---------
This module is the **canonical schema source** for MCP++ 1.0 schema identity
and generation (interface ``SchemaId@1``).  Versioned JSON Schema documents
under ``ipfs_accelerate_py/mcplusplus/schemas/`` are outputs of this source.
Language-local models (Python, TypeScript, Go, Rust) must agree with it;
disagreement is a hard failure under ``--check``.

Profile H 1.0 is the generation pattern: closed artifact kinds, schema markers
``mcp++/profile-h/<slug>@1.0``, and field inventories mirrored by the codecs.

Usage
-----
  python generate_schemas.py              # write managed JSON Schema files
  python generate_schemas.py --check      # fail on disk or language-model drift
  python generate_schemas.py --list       # print SchemaId@1 catalog
  python generate_schemas.py --fingerprint  # print canonical IR fingerprint

See ``schemas/README.md`` for tree layout and operator rules.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Sequence

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_PATH = Path(__file__).resolve()
MCPPLUSPLUS_ROOT = SCRIPT_PATH.parents[1]
SCHEMAS_ROOT = MCPPLUSPLUS_ROOT / "schemas"
REPO_HINTS = (
    MCPPLUSPLUS_ROOT.parent.parent,  # workspace root when nested
    MCPPLUSPLUS_ROOT.parent,  # ipfs_accelerate_py parent
)


def _repo_root() -> Path:
    """Locate the repository root that contains ipfs_accelerate_py/mcplusplus."""
    for candidate in (MCPPLUSPLUS_ROOT.parent.parent, *REPO_HINTS, Path.cwd()):
        probe = candidate / "ipfs_accelerate_py" / "mcplusplus" / "schemas"
        if probe.is_dir():
            return candidate
    # Fall back to package-relative layout.
    return MCPPLUSPLUS_ROOT.parent.parent


# ---------------------------------------------------------------------------
# SchemaId@1 — canonical registry
# ---------------------------------------------------------------------------

SCHEMA_DRAFT = "https://json-schema.org/draft/2020-12/schema"
SCHEMA_BASE_URL = "https://mcp-plus-plus.dev/schemas"


@dataclass(frozen=True)
class SchemaId:
    """SchemaId@1 catalog entry.

    ``schema_id`` is the stable logical identity (not a filesystem path).
    ``relative_path`` is under ``schemas/``.  ``interface`` is the plan
    interface label when one exists (e.g. McppJcsV1@1).
    """

    schema_id: str
    relative_path: str
    title: str
    family: str
    interface: str | None = None
    managed: bool = True  # regenerated by this script when True


# Managed catalog.  New schema families (execution envelope, StateRef, …)
# extend this list and add builders; hand-editing generated files is forbidden.
SCHEMA_CATALOG: tuple[SchemaId, ...] = (
    SchemaId(
        schema_id="mcp++/canonicalization/mcpp-jcs-v1@1",
        relative_path="canonicalization/mcpp-jcs-v1.schema.json",
        title="MCP++ mcpp-jcs-v1 canonicalization algorithm metadata (McppJcsV1@1)",
        family="canonicalization",
        interface="McppJcsV1@1",
        managed=False,  # authored under MCPP-024; checked for identity only
    ),
    SchemaId(
        schema_id="mcp++/profile-h/1.0/common@1",
        relative_path="profile-h/1.0/common.schema.json",
        title="MCP++ Profile H 1.0 common definitions",
        family="profile-h",
        interface="SchemaId@1",
        managed=True,
    ),
    SchemaId(
        schema_id="mcp++/profile-h/1.0/artifacts@1",
        relative_path="profile-h/1.0/artifacts.schema.json",
        title="MCP++ Profile H 1.0 canonical artifacts",
        family="profile-h",
        interface="SchemaId@1",
        managed=True,
    ),
    SchemaId(
        schema_id="mcp++/profile-h/1.0/x402-v2@1",
        relative_path="profile-h/1.0/x402-v2.schema.json",
        title="Profile H decoded x402 v2 transport objects",
        family="profile-h",
        interface="SchemaId@1",
        managed=True,
    ),
)


def catalog_by_path() -> dict[str, SchemaId]:
    return {entry.relative_path: entry for entry in SCHEMA_CATALOG}


# ---------------------------------------------------------------------------
# Profile H 1.0 — generation pattern (canonical IR)
# ---------------------------------------------------------------------------

PROFILE_H_VERSION = "1.0"
PROFILE_H_MARKER_PREFIX = "mcp++/profile-h"
COMMON_FIELDS: tuple[str, ...] = ("schema", "createdAt", "parents", "correlationId")

# Shared primitive fragments (JSON Schema 2020-12).
_CID = {"type": "string", "pattern": "^b[a-z2-7]+$", "maxLength": 128}
_DID = {
    "type": "string",
    "pattern": r"^did:[a-z0-9]+:[A-Za-z0-9._:%-]+(?:[/?#][^\u0000]*)?$",
    "maxLength": 512,
}
_TIME = {"type": "integer", "minimum": 0, "maximum": 9007199254740991}
_AMOUNT = {"type": "string", "pattern": "^(?:0|[1-9][0-9]{0,77})$"}
_NETWORK = {
    "type": "string",
    "pattern": r"^[a-z0-9-]{3,8}:[A-Za-z0-9_-]{1,32}$",
}
_SIG = {"type": "string", "pattern": r"^[A-Za-z0-9_-]{86}$"}
_REQUIREMENT = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "scheme",
        "network",
        "asset",
        "amount",
        "payTo",
        "maxTimeoutSeconds",
        "extra",
    ],
    "properties": {
        "scheme": {"type": "string", "minLength": 1, "maxLength": 64},
        "network": {"$ref": "#/$defs/network"},
        "asset": {"type": "string", "minLength": 1, "maxLength": 256},
        "amount": {"$ref": "#/$defs/amount"},
        "payTo": {"type": "string", "minLength": 1, "maxLength": 256},
        "maxTimeoutSeconds": {"type": "integer", "minimum": 1, "maximum": 3600},
        "extra": {"type": "object"},
    },
}


@dataclass(frozen=True)
class ArtifactKind:
    """One closed Profile H artifact kind in the canonical IR."""

    kind: str
    slug: str
    fields: tuple[str, ...]
    # Optional property overrides (defaults derived from field name heuristics).
    property_schema: Mapping[str, Any] = field(default_factory=dict)
    enums: Mapping[str, Sequence[str]] = field(default_factory=dict)
    nullable_fields: frozenset[str] = field(default_factory=frozenset)
    const_fields: Mapping[str, Any] = field(default_factory=dict)

    @property
    def schema_marker(self) -> str:
        return f"{PROFILE_H_MARKER_PREFIX}/{self.slug}@{PROFILE_H_VERSION}"


def _prop_for_field(
    name: str,
    *,
    enums: Mapping[str, Sequence[str]],
    nullable: frozenset[str],
    consts: Mapping[str, Any],
    time_alias: str = "time",
) -> dict[str, Any]:
    if name in consts:
        return {"const": consts[name]}
    if name == "schema":
        raise AssertionError("schema marker handled separately")
    if name in enums:
        schema: dict[str, Any] = {"enum": list(enums[name])}
    elif name.endswith("Cid") or name.endswith("Commitment"):
        schema = {"$ref": f"#/$defs/cid"}
    elif name.endswith("Did") or name in {"serverDid", "sellerDid", "verifierDid"}:
        schema = {"$ref": "#/$defs/did"}
    elif name in {
        "createdAt",
        "validFrom",
        "expiresAt",
        "verifiedAt",
        "settledAt",
        "recordedAt",
        "requestedAt",
        "decidedAt",
        "quotaUnits",
        "consumedUnits",
    }:
        schema = {"$ref": f"#/$defs/{time_alias}"}
    elif name == "amount":
        schema = {"$ref": "#/$defs/amount"}
    elif name == "network":
        schema = {"$ref": "#/$defs/network"}
    elif name == "signature":
        schema = {"$ref": "#/$defs/sig"}
    elif name == "signatureAlg":
        schema = {"const": "Ed25519"}
    elif name == "requirements":
        schema = {
            "type": "array",
            "minItems": 1,
            "maxItems": 32,
            "items": {"$ref": "#/$defs/requirement"},
        }
    elif name == "requirementIndex":
        schema = {"type": "integer", "minimum": 0, "maximum": 31}
    elif name == "units":
        schema = {"type": "integer", "minimum": 1, "maximum": 9007199254740991}
    elif name == "httpMethod":
        schema = {
            "type": ["string", "null"],
            "enum": ["GET", "POST", "PUT", "PATCH", "DELETE", None],
        }
    elif name == "httpRoute":
        schema = {"type": ["string", "null"], "maxLength": 512}
    elif name in {
        "operationName",
        "ability",
        "catalogVersion",
        "scheme",
        "asset",
        "payee",
        "nonce",
        "idempotencyKey",
        "reasonCode",
        "unit",
        "correlationId",
    }:
        max_len = {
            "operationName": 256,
            "ability": 256,
            "asset": 256,
            "payee": 256,
            "catalogVersion": 64,
            "scheme": 64,
            "unit": 128,
            "nonce": 128,
            "idempotencyKey": 128,
            "reasonCode": 128,
            "correlationId": 128,
        }.get(name, 256)
        schema = {"type": "string", "minLength": 1, "maxLength": max_len}
    else:
        schema = {"type": "string"}

    if name in nullable and "type" not in schema:
        schema = {"anyOf": [schema, {"type": "null"}]}
    elif name in nullable and schema.get("type") not in (["string", "null"],):
        if "$ref" in schema or "enum" in schema or "const" in schema:
            schema = {"anyOf": [schema, {"type": "null"}]}
    return schema


# Field inventories must match the Profile H codecs (tests-py/ts).  Order is
# normative for required arrays in generated JSON Schema.
PROFILE_H_ARTIFACTS: tuple[ArtifactKind, ...] = (
    ArtifactKind(
        kind="PaidCapability",
        slug="paid-capability",
        fields=(
            "serverDid",
            "descriptorCid",
            "interfaceCid",
            "operationKind",
            "operationName",
            "httpMethod",
            "httpRoute",
            "catalogVersion",
            "ability",
            "policyCid",
            "termsCid",
            "scheme",
            "network",
            "asset",
            "amount",
            "payee",
            "validFrom",
            "expiresAt",
            "settlementTiming",
            "sellerDid",
            "signatureAlg",
            "signature",
        ),
        enums={
            "operationKind": ("tool", "resource", "prompt", "http"),
            "settlementTiming": ("immediate", "metered", "batched"),
        },
    ),
    ArtifactKind(
        kind="PaymentQuote",
        slug="payment-quote",
        fields=(
            "capabilityCid",
            "catalogCid",
            "descriptorCid",
            "requestCid",
            "requirements",
            "nonce",
            "expiresAt",
            "idempotencyKey",
            "sellerDid",
            "signatureAlg",
            "signature",
        ),
    ),
    ArtifactKind(
        kind="PaymentAuthorization",
        slug="payment-authorization",
        fields=(
            "quoteCid",
            "requestCid",
            "requirementIndex",
            "paymentPayloadCid",
            "payerCommitment",
            "signedPayloadCommitment",
            "signatureCommitment",
        ),
    ),
    ArtifactKind(
        kind="PaymentVerification",
        slug="payment-verification",
        fields=(
            "authorizationCid",
            "verifierDid",
            "decision",
            "reasonCode",
            "verifiedAt",
            "expiresAt",
            "evidenceCid",
        ),
        enums={"decision": ("verified", "rejected")},
    ),
    ArtifactKind(
        kind="SettlementReceipt",
        slug="settlement-receipt",
        fields=(
            "verificationCid",
            "outcome",
            "amount",
            "network",
            "networkReferenceCommitment",
            "disclosurePolicy",
            "paymentResponseCid",
            "settledAt",
        ),
        enums={
            "outcome": (
                "settled",
                "failed",
                "pending",
                "reconciliation-required",
                "refunded",
            ),
            "disclosurePolicy": ("commitment-only", "authorized", "public"),
        },
    ),
    ArtifactKind(
        kind="PaidEntitlement",
        slug="paid-entitlement",
        fields=(
            "settlementCid",
            "subjectCommitment",
            "capabilityCid",
            "quotaUnits",
            "consumedUnits",
            "unit",
            "expiresAt",
        ),
    ),
    ArtifactKind(
        kind="UsageRecord",
        slug="usage-record",
        fields=(
            "entitlementCid",
            "unit",
            "inputCid",
            "outputCid",
            "units",
            "recordedAt",
        ),
    ),
    ArtifactKind(
        kind="RefundRecord",
        slug="refund-record",
        fields=(
            "settlementCid",
            "requestCid",
            "decision",
            "outcome",
            "evidenceCid",
            "requestedAt",
            "decidedAt",
        ),
        enums={
            "decision": ("requested", "approved", "denied"),
            "outcome": ("pending", "refunded", "failed", "not-applicable"),
        },
    ),
    ArtifactKind(
        kind="AccessReceipt",
        slug="access-receipt",
        fields=(
            "operationName",
            "requestCid",
            "ucanDecisionCid",
            "policyDecisionCid",
            "leaseDecisionCid",
            "commercialEvidenceCid",
            "decision",
            "resultCid",
            "reasonCode",
            "decidedAt",
        ),
        enums={"decision": ("allow", "deny")},
        nullable_fields=frozenset(
            {
                "ucanDecisionCid",
                "policyDecisionCid",
                "leaseDecisionCid",
                "commercialEvidenceCid",
                "resultCid",
            }
        ),
    ),
)


def profile_h_schemas_map() -> dict[str, str]:
    return {a.kind: a.slug for a in PROFILE_H_ARTIFACTS}


def profile_h_fields_map() -> dict[str, list[str]]:
    return {a.kind: list(a.fields) for a in PROFILE_H_ARTIFACTS}


def profile_h_markers_map() -> dict[str, str]:
    return {a.kind: a.schema_marker for a in PROFILE_H_ARTIFACTS}


# ---------------------------------------------------------------------------
# Builders — emit JSON Schema documents from the canonical IR
# ---------------------------------------------------------------------------


def _schema_id_url(relative_path: str) -> str:
    return f"{SCHEMA_BASE_URL}/{relative_path}"


def build_profile_h_common() -> dict[str, Any]:
    return {
        "$schema": SCHEMA_DRAFT,
        "$id": _schema_id_url("profile-h/1.0/common.schema.json"),
        "title": "MCP++ Profile H 1.0 common definitions",
        "$defs": {
            "cid": dict(_CID),
            "did": dict(_DID),
            "timestamp": dict(_TIME),
            "amount": dict(_AMOUNT),
            "network": dict(_NETWORK),
            "signature": dict(_SIG),
            "requirement": json.loads(json.dumps(_REQUIREMENT)),
        },
    }


def build_profile_h_artifacts() -> dict[str, Any]:
    defs: dict[str, Any] = {
        "cid": dict(_CID),
        "did": dict(_DID),
        "time": dict(_TIME),
        "amount": dict(_AMOUNT),
        "network": dict(_NETWORK),
        "sig": dict(_SIG),
        "common": {
            "type": "object",
            "required": list(COMMON_FIELDS),
            "properties": {
                "schema": {"type": "string"},
                "createdAt": {"$ref": "#/$defs/time"},
                "parents": {
                    "type": "array",
                    "maxItems": 256,
                    "uniqueItems": True,
                    "items": {"$ref": "#/$defs/cid"},
                },
                "correlationId": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 128,
                },
            },
        },
        "requirement": json.loads(json.dumps(_REQUIREMENT)),
    }

    for artifact in PROFILE_H_ARTIFACTS:
        required = list(COMMON_FIELDS) + list(artifact.fields)
        properties: dict[str, Any] = {
            "schema": {"const": artifact.schema_marker},
            "createdAt": {"$ref": "#/$defs/time"},
            "parents": {"type": "array", "items": {"$ref": "#/$defs/cid"}},
            "correlationId": {"type": "string"},
        }
        for name in artifact.fields:
            if name in artifact.property_schema:
                properties[name] = dict(artifact.property_schema[name])
            else:
                properties[name] = _prop_for_field(
                    name,
                    enums=artifact.enums,
                    nullable=artifact.nullable_fields,
                    consts=artifact.const_fields,
                    time_alias="time",
                )
        defs[artifact.kind] = {
            "allOf": [
                {"$ref": "#/$defs/common"},
                {
                    "type": "object",
                    "additionalProperties": False,
                    "required": required,
                    "properties": properties,
                },
            ]
        }

    return {
        "$schema": SCHEMA_DRAFT,
        "$id": _schema_id_url("profile-h/1.0/artifacts.schema.json"),
        "title": "MCP++ Profile H 1.0 canonical artifacts",
        "description": (
            "Closed DAG-JSON shapes. Semantic, CID codec, expiry, redaction, "
            "and negotiated-bound checks are additionally enforced by the "
            "Profile H codecs."
        ),
        "oneOf": [{"$ref": f"#/$defs/{a.kind}"} for a in PROFILE_H_ARTIFACTS],
        "$defs": defs,
    }


def build_profile_h_x402_v2() -> dict[str, Any]:
    requirement = {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "scheme",
            "network",
            "asset",
            "amount",
            "payTo",
            "maxTimeoutSeconds",
            "extra",
        ],
        "properties": {
            "scheme": {"type": "string", "minLength": 1},
            "network": {"$ref": "#/$defs/network"},
            "asset": {"type": "string", "minLength": 1},
            "amount": {"$ref": "#/$defs/amount"},
            "payTo": {"type": "string", "minLength": 1},
            "maxTimeoutSeconds": {
                "type": "integer",
                "minimum": 1,
                "maximum": 3600,
            },
            "extra": {"type": "object"},
        },
    }
    return {
        "$schema": SCHEMA_DRAFT,
        "$id": _schema_id_url("profile-h/1.0/x402-v2.schema.json"),
        "title": "Profile H decoded x402 v2 transport objects",
        "description": (
            "Transport-only objects. PAYMENT-REQUIRED and PAYMENT-SIGNATURE "
            "are standard padded base64 of canonical UTF-8 JSON; "
            "PAYMENT-RESPONSE uses the same codec."
        ),
        "oneOf": [
            {"$ref": "#/$defs/PaymentRequired"},
            {"$ref": "#/$defs/PaymentPayload"},
            {"$ref": "#/$defs/SettlementResponse"},
        ],
        "$defs": {
            "network": dict(_NETWORK),
            "amount": dict(_AMOUNT),
            "requirement": requirement,
            "PaymentRequired": {
                "type": "object",
                "additionalProperties": False,
                "required": ["x402Version", "accepts"],
                "properties": {
                    "x402Version": {"const": 2},
                    "error": {"type": "string"},
                    "resource": {"type": "object"},
                    "accepts": {
                        "type": "array",
                        "minItems": 1,
                        "maxItems": 32,
                        "items": {"$ref": "#/$defs/requirement"},
                    },
                    "extensions": {"type": "object"},
                },
            },
            "PaymentPayload": {
                "type": "object",
                "additionalProperties": False,
                "required": ["x402Version", "accepted", "payload"],
                "properties": {
                    "x402Version": {"const": 2},
                    "resource": {"type": "object"},
                    "accepted": {"$ref": "#/$defs/requirement"},
                    "payload": {"type": "object"},
                    "extensions": {"type": "object"},
                },
            },
            "SettlementResponse": {
                "type": "object",
                "additionalProperties": False,
                "required": ["success", "network"],
                "properties": {
                    "success": {"type": "boolean"},
                    "errorReason": {"type": "string"},
                    "transaction": {"type": ["string", "null"]},
                    "network": {"$ref": "#/$defs/network"},
                    "payer": {"type": "string"},
                    "extensions": {"type": "object"},
                },
            },
        },
    }


BUILDERS: dict[str, Callable[[], dict[str, Any]]] = {
    "profile-h/1.0/common.schema.json": build_profile_h_common,
    "profile-h/1.0/artifacts.schema.json": build_profile_h_artifacts,
    "profile-h/1.0/x402-v2.schema.json": build_profile_h_x402_v2,
}


def render_json(document: Mapping[str, Any]) -> str:
    """Stable UTF-8 JSON with trailing newline (generated-file convention)."""
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def canonical_fingerprint() -> str:
    """SHA-256 of the closed Profile H IR + catalog ids (not pretty-print)."""
    payload = {
        "interface": "SchemaId@1",
        "catalog": [
            {
                "schema_id": e.schema_id,
                "relative_path": e.relative_path,
                "family": e.family,
                "managed": e.managed,
                "interface": e.interface,
            }
            for e in SCHEMA_CATALOG
        ],
        "profile_h": {
            "version": PROFILE_H_VERSION,
            "common_fields": list(COMMON_FIELDS),
            "artifacts": [
                {
                    "kind": a.kind,
                    "slug": a.slug,
                    "marker": a.schema_marker,
                    "fields": list(a.fields),
                    "enums": {k: list(v) for k, v in a.enums.items()},
                    "nullable": sorted(a.nullable_fields),
                }
                for a in PROFILE_H_ARTIFACTS
            ],
        },
    }
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


# ---------------------------------------------------------------------------
# Generate
# ---------------------------------------------------------------------------


def iter_managed_outputs() -> Iterable[tuple[str, dict[str, Any]]]:
    for relative, builder in BUILDERS.items():
        yield relative, builder()


def write_schemas(schemas_root: Path, *, dry_run: bool = False) -> list[str]:
    written: list[str] = []
    for relative, document in iter_managed_outputs():
        path = schemas_root / relative
        text = render_json(document)
        if dry_run:
            written.append(relative)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(relative)
    return written


# ---------------------------------------------------------------------------
# Extractors — disk schemas and language models
# ---------------------------------------------------------------------------


class DriftError(Exception):
    """One or more schema drift findings."""

    def __init__(self, findings: Sequence[str]) -> None:
        self.findings = list(findings)
        super().__init__("\n".join(self.findings))


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def extract_artifact_ir_from_schema(document: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    """Extract kind → {marker, fields} from a Profile H artifacts schema."""
    defs = document.get("$defs")
    if not isinstance(defs, Mapping):
        raise ValueError("artifacts schema missing $defs")
    out: dict[str, dict[str, Any]] = {}
    for kind, body in defs.items():
        if not isinstance(kind, str) or not kind[:1].isupper():
            continue
        if not isinstance(body, Mapping):
            continue
        marker = None
        required: list[str] = []
        for part in body.get("allOf") or ():
            if not isinstance(part, Mapping):
                continue
            props = part.get("properties") or {}
            if "schema" in props and isinstance(props["schema"], Mapping):
                marker = props["schema"].get("const")
            if "required" in part and isinstance(part["required"], list):
                required = [str(x) for x in part["required"]]
        if marker is None:
            continue
        specific = [f for f in required if f not in COMMON_FIELDS]
        out[kind] = {"marker": marker, "fields": specific}
    return out


def _parse_python_string_dict(source: str, name: str) -> dict[str, str]:
    """Parse ``NAME = { "K": "v", ... }`` assignments from Python source."""
    pattern = rf"^{name}\s*=\s*\{{(.*?)^\}}"
    match = re.search(pattern, source, flags=re.MULTILINE | re.DOTALL)
    if not match:
        raise ValueError(f"could not find {name} dict in Python source")
    # Reconstruct a literal and evaluate safely via json after quote normalize.
    body = "{" + match.group(1) + "}"
    # Allow trailing commas by using ast.literal_eval.
    import ast

    value = ast.literal_eval(body)
    if not isinstance(value, dict):
        raise ValueError(f"{name} is not a dict")
    return {str(k): str(v) for k, v in value.items()}


def extract_python_profile_h(path: Path) -> tuple[dict[str, str], dict[str, list[str]]]:
    text = path.read_text(encoding="utf-8")
    schemas = _parse_python_string_dict(text, "SCHEMAS")
    # FIELDS values may be space-separated strings before the split rewrite.
    pattern = r"^FIELDS\s*=\s*\{(.*?)^\}"
    match = re.search(pattern, text, flags=re.MULTILINE | re.DOTALL)
    if not match:
        raise ValueError("could not find FIELDS dict in Python Profile H codec")
    import ast

    raw = ast.literal_eval("{" + match.group(1) + "}")
    fields: dict[str, list[str]] = {}
    for key, value in raw.items():
        if isinstance(value, str):
            fields[str(key)] = value.split()
        elif isinstance(value, (list, tuple)):
            fields[str(key)] = [str(x) for x in value]
        else:
            raise ValueError(f"unexpected FIELDS value type for {key}")
    return schemas, fields


def extract_typescript_profile_h(path: Path) -> tuple[dict[str, str], dict[str, list[str]]]:
    text = path.read_text(encoding="utf-8")
    schemas: dict[str, str] = {}
    for kind, slug in re.findall(
        r"([A-Za-z][A-Za-z0-9]*)\s*:\s*'([a-z0-9-]+)'",
        _slice_ts_object(text, "SCHEMAS"),
    ):
        schemas[kind] = slug

    fields_body = _slice_ts_object(text, "FIELDS")
    fields: dict[str, list[str]] = {}
    # Entries look like: Kind:'a b c'.split(' ')  or Kind: 'a b c'.split(" ")
    for kind, field_str in re.findall(
        r"([A-Za-z][A-Za-z0-9]*)\s*:\s*'([^']+)'\s*\.split\s*\(\s*['\"] ['\"]\s*\)",
        fields_body,
    ):
        fields[kind] = field_str.split()
    if not fields:
        # Alternate: Kind:['a','b'] form
        for kind, arr in re.findall(
            r"([A-Za-z][A-Za-z0-9]*)\s*:\s*\[([^\]]+)\]",
            fields_body,
        ):
            fields[kind] = re.findall(r"['\"]([A-Za-z0-9]+)['\"]", arr)
    return schemas, fields


def _slice_ts_object(source: str, name: str) -> str:
    # Match `const NAME:...={...}` or `const NAME={...}`
    match = re.search(
        rf"(?:const|let|var)\s+{name}\s*(?::[^=]+)?=\s*\{{",
        source,
    )
    if not match:
        raise ValueError(f"could not find TypeScript object {name}")
    start = match.end() - 1
    depth = 0
    for idx in range(start, len(source)):
        ch = source[idx]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return source[start + 1 : idx]
    raise ValueError(f"unbalanced braces for TypeScript object {name}")


def extract_go_profile_h_markers(path: Path) -> dict[str, str] | None:
    """Optional Go markers; returns None when Profile H is not yet modeled."""
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8")
    if "profile-h" not in text and "PaidCapability" not in text:
        return None
    found = dict(
        re.findall(
            r'"(Paid\w+|Payment\w+|Settlement\w+|Usage\w+|Refund\w+|Access\w+)"\s*:\s*"([^"]+)"',
            text,
        )
    )
    return found or None


def extract_rust_profile_h_markers(path: Path) -> dict[str, str] | None:
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8")
    if "profile-h" not in text and "PaidCapability" not in text:
        return None
    found = dict(
        re.findall(
            r'"(Paid\w+|Payment\w+|Settlement\w+|Usage\w+|Refund\w+|Access\w+)"\s*=>\s*"([^"]+)"',
            text,
        )
    )
    return found or None


# ---------------------------------------------------------------------------
# Drift checks
# ---------------------------------------------------------------------------


@dataclass
class LanguageModelSource:
    language: str
    relative_path: str
    required: bool = True


LANGUAGE_MODELS: tuple[LanguageModelSource, ...] = (
    LanguageModelSource(
        "python",
        "ipfs_accelerate_py/mcplusplus/tests-py/validators/profile_h.py",
        required=True,
    ),
    LanguageModelSource(
        "typescript",
        "ipfs_accelerate_py/mcplusplus/tests-ts/src/profileH.ts",
        required=True,
    ),
    LanguageModelSource(
        "go",
        "ipfs_accelerate_py/mcplusplus/tests-go/models.go",
        required=False,
    ),
    LanguageModelSource(
        "rust",
        "ipfs_accelerate_py/mcplusplus/tests-rs/src/models.rs",
        required=False,
    ),
)


def check_catalog_files(schemas_root: Path) -> list[str]:
    findings: list[str] = []
    for entry in SCHEMA_CATALOG:
        path = schemas_root / entry.relative_path
        if not path.is_file():
            findings.append(
                f"catalog: missing schema file for {entry.schema_id}: "
                f"{entry.relative_path}"
            )
            continue
        try:
            doc = _load_json(path)
        except json.JSONDecodeError as exc:
            findings.append(f"catalog: invalid JSON at {entry.relative_path}: {exc}")
            continue
        if not isinstance(doc, dict):
            findings.append(f"catalog: {entry.relative_path} root must be an object")
            continue
        expected_id = _schema_id_url(entry.relative_path)
        actual_id = doc.get("$id")
        if actual_id != expected_id:
            findings.append(
                f"catalog: {entry.relative_path} $id drift: "
                f"expected {expected_id!r}, got {actual_id!r}"
            )
        if entry.family == "canonicalization":
            algo = (
                (doc.get("$defs") or {}).get("algorithmId") or {}
            )
            if isinstance(algo, dict) and algo.get("const") != "mcpp-jcs-v1":
                findings.append(
                    f"catalog: {entry.relative_path} algorithmId const must be "
                    f"mcpp-jcs-v1 (McppJcsV1@1)"
                )
    return findings


def check_managed_generation(schemas_root: Path) -> list[str]:
    """Compare managed on-disk documents to builders (structural Profile H IR).

    Full pretty-print equality is not required for pre-existing compact
    documents; the closed kind/marker/field IR must match exactly.  For
    common and x402, deep equality of the JSON value is required after load.
    """
    findings: list[str] = []
    expected_artifacts = build_profile_h_artifacts()
    expected_ir = extract_artifact_ir_from_schema(expected_artifacts)

    artifacts_path = schemas_root / "profile-h/1.0/artifacts.schema.json"
    if artifacts_path.is_file():
        disk_doc = _load_json(artifacts_path)
        try:
            disk_ir = extract_artifact_ir_from_schema(disk_doc)
        except ValueError as exc:
            findings.append(f"disk artifacts schema: {exc}")
            disk_ir = {}
        if set(disk_ir) != set(expected_ir):
            findings.append(
                "disk artifacts schema kinds disagree with canonical source: "
                f"disk={sorted(disk_ir)} canonical={sorted(expected_ir)}"
            )
        for kind in sorted(set(expected_ir) & set(disk_ir)):
            if disk_ir[kind]["marker"] != expected_ir[kind]["marker"]:
                findings.append(
                    f"disk artifacts schema marker drift for {kind}: "
                    f"disk={disk_ir[kind]['marker']!r} "
                    f"canonical={expected_ir[kind]['marker']!r}"
                )
            if disk_ir[kind]["fields"] != expected_ir[kind]["fields"]:
                findings.append(
                    f"disk artifacts schema field drift for {kind}: "
                    f"disk={disk_ir[kind]['fields']} "
                    f"canonical={expected_ir[kind]['fields']}"
                )
        # oneOf coverage
        one_of = disk_doc.get("oneOf") or []
        refs = {
            item.get("$ref", "").rsplit("/", 1)[-1]
            for item in one_of
            if isinstance(item, Mapping)
        }
        expected_kinds = {a.kind for a in PROFILE_H_ARTIFACTS}
        if refs != expected_kinds:
            findings.append(
                f"disk artifacts schema oneOf drift: disk={sorted(refs)} "
                f"canonical={sorted(expected_kinds)}"
            )
    else:
        findings.append("disk: missing profile-h/1.0/artifacts.schema.json")

    # common + x402: deep equality after JSON round-trip (formatting-insensitive)
    for relative, builder in (
        ("profile-h/1.0/common.schema.json", build_profile_h_common),
        ("profile-h/1.0/x402-v2.schema.json", build_profile_h_x402_v2),
    ):
        path = schemas_root / relative
        if not path.is_file():
            findings.append(f"disk: missing {relative}")
            continue
        disk_doc = _load_json(path)
        expected = builder()
        if disk_doc != expected:
            # Allow equivalent documents that only differ in non-semantic key
            # order by comparing canonical dumps.
            if _canonical_json(disk_doc) != _canonical_json(expected):
                findings.append(
                    f"disk schema disagrees with canonical source: {relative}"
                )
    return findings


def _canonical_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def check_language_models(repo_root: Path) -> list[str]:
    findings: list[str] = []
    expected_schemas = profile_h_schemas_map()
    expected_fields = profile_h_fields_map()
    expected_markers = profile_h_markers_map()

    for model in LANGUAGE_MODELS:
        path = repo_root / model.relative_path
        if not path.is_file():
            if model.required:
                findings.append(
                    f"language model missing ({model.language}): "
                    f"{model.relative_path}"
                )
            continue

        try:
            if model.language == "python":
                schemas, fields = extract_python_profile_h(path)
            elif model.language == "typescript":
                schemas, fields = extract_typescript_profile_h(path)
            elif model.language == "go":
                markers = extract_go_profile_h_markers(path)
                if markers is None:
                    continue  # not yet modeled — not a drift failure
                schemas = markers
                fields = {}
            elif model.language == "rust":
                markers = extract_rust_profile_h_markers(path)
                if markers is None:
                    continue
                schemas = markers
                fields = {}
            else:
                findings.append(f"unknown language model: {model.language}")
                continue
        except ValueError as exc:
            findings.append(
                f"language model parse failed ({model.language} "
                f"{model.relative_path}): {exc}"
            )
            continue

        if schemas != expected_schemas and model.language in {"python", "typescript"}:
            # SCHEMAS maps kind → slug
            if set(schemas) != set(expected_schemas):
                findings.append(
                    f"language model {model.language} kind set disagrees with "
                    f"canonical source: model={sorted(schemas)} "
                    f"canonical={sorted(expected_schemas)}"
                )
            for kind in sorted(set(schemas) & set(expected_schemas)):
                if schemas[kind] != expected_schemas[kind]:
                    findings.append(
                        f"language model {model.language} slug drift for {kind}: "
                        f"model={schemas[kind]!r} "
                        f"canonical={expected_schemas[kind]!r}"
                    )
        elif schemas and model.language in {"go", "rust"}:
            # May store full markers or slugs.
            for kind, value in schemas.items():
                if kind not in expected_markers:
                    findings.append(
                        f"language model {model.language} unknown kind {kind}"
                    )
                    continue
                if value not in {expected_schemas.get(kind), expected_markers[kind]}:
                    findings.append(
                        f"language model {model.language} marker/slug drift for "
                        f"{kind}: model={value!r}"
                    )

        if fields:
            if set(fields) != set(expected_fields):
                findings.append(
                    f"language model {model.language} field-kind set disagrees: "
                    f"model={sorted(fields)} canonical={sorted(expected_fields)}"
                )
            for kind in sorted(set(fields) & set(expected_fields)):
                if fields[kind] != expected_fields[kind]:
                    findings.append(
                        f"language model {model.language} field drift for {kind}: "
                        f"model={fields[kind]} canonical={expected_fields[kind]}"
                    )

        # Marker string presence check for required models.
        if model.language in {"python", "typescript"}:
            text = path.read_text(encoding="utf-8")
            for kind, marker in expected_markers.items():
                # Codecs compose markers as f"mcp++/profile-h/{slug}@1.0"
                slug = expected_schemas[kind]
                if slug not in text and marker not in text:
                    findings.append(
                        f"language model {model.language} missing schema slug "
                        f"for {kind}: {slug}"
                    )

    return findings


def run_check(repo_root: Path, schemas_root: Path) -> None:
    findings: list[str] = []
    findings.extend(check_catalog_files(schemas_root))
    findings.extend(check_managed_generation(schemas_root))
    findings.extend(check_language_models(repo_root))
    if findings:
        raise DriftError(findings)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate MCP++ JSON Schemas from the canonical SchemaId@1 source "
            "and check language-model drift."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Verify on-disk schemas and language models agree with the "
            "canonical source; exit 1 on drift."
        ),
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Print the SchemaId@1 catalog and exit.",
    )
    parser.add_argument(
        "--fingerprint",
        action="store_true",
        help="Print the SHA-256 fingerprint of the canonical IR and exit.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="With generate mode, list files that would be written.",
    )
    parser.add_argument(
        "--schemas-root",
        type=Path,
        default=None,
        help="Override schemas directory (default: package schemas/).",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Override repository root for language-model paths.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)

    schemas_root = (args.schemas_root or SCHEMAS_ROOT).resolve()
    repo_root = (args.repo_root or _repo_root()).resolve()

    if args.list:
        for entry in SCHEMA_CATALOG:
            managed = "managed" if entry.managed else "frozen"
            iface = entry.interface or "-"
            print(
                f"{entry.schema_id}\t{entry.relative_path}\t{iface}\t{managed}"
            )
        print(f"fingerprint\t{canonical_fingerprint()}", file=sys.stderr)
        return 0

    if args.fingerprint:
        print(canonical_fingerprint())
        return 0

    if args.check:
        try:
            run_check(repo_root, schemas_root)
        except DriftError as exc:
            print("SCHEMA DRIFT DETECTED (SchemaId@1)", file=sys.stderr)
            for line in exc.findings:
                print(f"  - {line}", file=sys.stderr)
            print(
                "\nCanonical source: "
                "ipfs_accelerate_py/mcplusplus/scripts/generate_schemas.py",
                file=sys.stderr,
            )
            print(
                "Fix: align language models with the IR, or re-run without "
                "--check to regenerate managed JSON Schema files.",
                file=sys.stderr,
            )
            return 1
        print(
            f"OK: schemas and language models agree with canonical source "
            f"(fingerprint {canonical_fingerprint()[:16]}…)"
        )
        return 0

    # Default: generate managed schemas from the canonical source.
    written = write_schemas(schemas_root, dry_run=args.dry_run)
    action = "would write" if args.dry_run else "wrote"
    for relative in written:
        print(f"{action}: {schemas_root / relative}")
    print(f"{action} {len(written)} managed schema file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
